# Copyright the Velero contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

ARG OS_VERSION=1809

FROM --platform=$BUILDPLATFORM golang:1.22-bookworm AS build

ARG TARGETOS
ARG TARGETARCH
ARG TARGETVARIANT
ARG GOPROXY

ENV GOOS=${TARGETOS} \
    GOARCH=${TARGETARCH} \
    GOARM=${TARGETVARIANT} \
    GOPROXY=${GOPROXY}

COPY . /go/src/velero-plugin-for-aws
WORKDIR /go/src/velero-plugin-for-aws
RUN export GOARM=$( echo "${GOARM}" | cut -c2-) && \
    CGO_ENABLED=0 go build -v -o /output/velero-plugin-for-aws.exe ./velero-plugin-for-aws && \
    CGO_ENABLED=0 go build -v -o /output/cp-plugin.exe ./hack/cp-plugin

FROM mcr.microsoft.com/windows/nanoserver:${OS_VERSION}
COPY --from=build /output/velero-plugin-for-aws.exe /
COPY --from=build /output/cp-plugin.exe /
USER ContainerUser
ENTRYPOINT ["/cp-plugin.exe", "/velero-plugin-for-aws.exe", "/target/velero-plugin-for-aws.exe"]